### ISSUE TITLE
Texture failed to load for all added mooblooms (not the yellow one from the base friends and foes mod)

### ISSUE THREAD

**Issue by uczpre** [Faboslav/friends-and-foes-flowery-mooblooms#7]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.16.2 fabric

### Mod version information

flowey mooblooms 2.0.2 , friends and foes 2.0.16

### Expected Behavior

Textures to load

### Actual Behavior

texture does load :D

### Reproduction Steps

Spawn it :D

Error log with iris 1.7.0 :

java.io.FileNotFoundException: friendsandfoes:textures/entity/moobloom/moobloom_azure_bluet.png
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at software.bernie.geckolib.cache.texture.AnimatableTexture.method_4625(AnimatableTexture.java:39) ~[geckolib-fabric-1.20.1-4.4.7.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.handler$dmh000$geckolib$wrapAnimatableTexture(class_1060.java:1029) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668$class_4683.method_23563(class_4668.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1079) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at net.irisshaders.iris.layer.OuterWrappedRenderType.method_23516(OuterWrappedRenderType.java:42) ~[iris-1.7.0+mc1.20.1.jar:?]
	at net.irisshaders.batchedentityrendering.impl.FullyBufferedMultiBufferSource.method_22993(FullyBufferedMultiBufferSource.java:145) ~[iris-1.7.0+mc1.20.1.jar:?]
	at net.minecraft.class_761.handler$edj000$iris$batchedentityrendering$beginTranslucents(class_761.java:3996) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1493) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]

-----------------------------------------------------------------------------------------------------------------

Error log without iris/shaders :

java.io.FileNotFoundException: friendsandfoes:textures/entity/moobloom/moobloom_peony.png
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at software.bernie.geckolib.cache.texture.AnimatableTexture.method_4625(AnimatableTexture.java:39) ~[geckolib-fabric-1.20.1-4.4.7.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.handler$dmg000$geckolib$wrapAnimatableTexture(class_1060.java:1029) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668$class_4683.method_23563(class_4668.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1079) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_1921.method_23012(class_1921.java:864) ~[client-intermediary.jar:?]
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_4597$class_4598.getBuffer(class_4597.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_776.method_3353(class_776.java:109) ~[client-intermediary.jar:?]
	at com.faboslav.friendsandfoes.client.render.entity.feature.MoobloomFlowerFeatureRenderer.renderFlower(MoobloomFlowerFeatureRenderer.java:112) ~[friendsandfoes-fabric-mc1.20.1-2.0.16.jar:?]
	at com.faboslav.friendsandfoes.client.render.entity.feature.MoobloomFlowerFeatureRenderer.render(MoobloomFlowerFeatureRenderer.java:72) ~[friendsandfoes-fabric-mc1.20.1-2.0.16.jar:?]
	at com.faboslav.friendsandfoes.client.render.entity.feature.MoobloomFlowerFeatureRenderer.method_4199(MoobloomFlowerFeatureRenderer.java:22) ~[friendsandfoes-fabric-mc1.20.1-2.0.16.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_927.method_4072(class_927.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_927.method_3936(class_927.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1574) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1324) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]

### Screenshots & files

![Screenshot_20240824_114557](https://github.com/user-attachments/assets/3884d5fc-42ce-456b-b18f-7d116403b1ef)

**Comment by uczpre** [comment]
Could it be because i have the iris mod loaded ?

**Comment by uczpre** [comment]
nope , same bug appears without iris :/

**Comment by uczpre** [comment]
i forgot to install the mod on the client's end , sorry lol.
